import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                background: '#f8f9ff',
                'on-background': '#0b1c30',
                surface: '#f8f9ff',
                'on-surface': '#0b1c30',
                'on-surface-variant': '#464555',
                'surface-variant': '#d3e4fe',
                'surface-dim': '#cbdbf5',
                'surface-bright': '#f8f9ff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#eff4ff',
                'surface-container': '#e5eeff',
                'surface-container-high': '#dce9ff',
                'surface-container-highest': '#d3e4fe',
                'surface-tint': '#4d44e3',
                primary: '#3525cd',
                'on-primary': '#ffffff',
                'primary-container': '#4f46e5',
                'on-primary-container': '#dad7ff',
                'primary-fixed': '#e2dfff',
                'primary-fixed-dim': '#c3c0ff',
                'on-primary-fixed': '#0f0069',
                'on-primary-fixed-variant': '#3323cc',
                'inverse-primary': '#c3c0ff',
                'inverse-surface': '#213145',
                'inverse-on-surface': '#eaf1ff',
                secondary: '#006c49',
                'on-secondary': '#ffffff',
                'secondary-container': '#6cf8bb',
                'on-secondary-container': '#00714d',
                'secondary-fixed': '#6ffbbe',
                'secondary-fixed-dim': '#4edea3',
                'on-secondary-fixed': '#002113',
                'on-secondary-fixed-variant': '#005236',
                tertiary: '#960014',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#bc1d25',
                'on-tertiary-container': '#ffd0cc',
                'tertiary-fixed': '#ffdad7',
                'tertiary-fixed-dim': '#ffb3ad',
                'on-tertiary-fixed': '#410004',
                'on-tertiary-fixed-variant': '#930013',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                outline: '#777587',
                'outline-variant': '#c7c4d8',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                sm: '16px',
                lg: '32px',
                gutter: '20px',
                base: '4px',
                xl: '48px',
                'container-max': '1200px',
                xs: '8px',
                md: '24px',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
            },
            fontSize: {
                'otp-display': ['36px', { lineHeight: '44px', letterSpacing: '0.1em', fontWeight: '600' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
                'code-sm': ['14px', { lineHeight: '20px', fontWeight: '500' }],
            },
        },
    },

    plugins: [forms],
};
